
            executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2017/run_TSA_iter_1.sh
            arguments               = --mass_point 5
            log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2017/log/file_iter_1_Mass5.log
            output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2017/out/file_iter_1_Mass5.out
            error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2017/err/file_iter_1_Mass5.err
            +MaxRuntime             = 72000
            x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
            RequestCPUs             = 4
            queue 1
            