
            executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2016/run_TSA_iter_1.sh
            arguments               = --mass_point 1
            log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2016/log/file_iter_1_Mass1.log
            output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2016/out/file_iter_1_Mass1.out
            error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2016/err/file_iter_1_Mass1.err
            +MaxRuntime             = 36000
            x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
            RequestCPUs             = 4
            queue 1
            