
            executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2017/run_TSA_allOR.sh
            arguments               = --mass_point 3
            log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2017/log/file_allOR_Mass3.log
            output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2017/out/file_allOR_Mass3.out
            error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2017/err/file_allOR_Mass3.err
            +MaxRuntime             = 10800
            x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
            RequestCPUs             = 4
            queue 1
            