
            executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2018/run_TSA_iter_0.sh
            arguments               = --mass_point 19
            log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2018/log/file_iter_0_Mass19.log
            output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2018/out/file_iter_0_Mass19.out
            error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_muTau_2018/err/file_iter_0_Mass19.err
            +MaxRuntime             = 21600
            x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
            RequestCPUs             = 4
            queue 1
            