
    executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/run_TSA.sh
    arguments               = --mass_point $(ProcId)
    log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/file_$(ClusterId).$(ProcId).log
    output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/file_$(ClusterId).$(ProcId).out
    error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/file_$(ClusterId).$(ProcId).err
    +MaxRuntime             = 21600
    x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
    RequestCPUs             = 4
    queue 4,25,16
    