
    executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2017/run_TSA_baseline.sh
    arguments               = --mass_point $(ProcId)
    log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2017/log/file_$(ClusterId).$(ProcId).log
    output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2017/out/file_$(ClusterId).$(ProcId).out
    error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2017/err/file_$(ClusterId).$(ProcId).err
    +MaxRuntime             = 3600
    x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
    RequestCPUs             = 4
    queue 25
    