
            executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/run_TSA_baseline.sh
            arguments               = --mass_point 12
            log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/log/file_baseline_Mass12.log
            output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/out/file_baseline_Mass12.out
            error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_eTau_2018/err/file_baseline_Mass12.err
            +MaxRuntime             = 3600
            x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
            RequestCPUs             = 4
            queue 1
            