
            executable              = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2018/run_TSA_iter_2.sh
            arguments               = --mass_point 7
            log                     = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2018/log/file_iter_2_Mass7.log
            output                  = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2018/out/file_iter_2_Mass7.out
            error                   = /afs/cern.ch/work/v/vdamante/public/analysis/output/GluGlu_Radion_tauTau_2018/err/file_iter_2_Mass7.err
            +MaxRuntime             = 18000
            x509userproxy           = /afs/cern.ch/work/v/vdamante/public/analysis/x509up_u127699
            RequestCPUs             = 4
            queue 1
            